
-- CALENDAR Table for months (not using)
-- DROP TABLE IF EXISTS calendar;
-- CREATE TABLE calendar (
--   id VARCHAR(100),
--   month_Name VARCHAR(100)
-- ); 

-- INSERT INTO calendar (id , month_Name)
-- VALUES ('1','January'),('2','February'),('3','March'),('4','April'),('5','May'),('6','June'),('7','July'),('8','August'),('9','September'),('10','October'),('11','November'),('12','December');

-- Comparative TABLE veggies of month
DROP TABLE IF EXISTS month_veggies;

CREATE TABLE month_veggies (
  country_fk varchar(100) DEFAULT NULL,
  month_fk varchar(100) DEFAULT NULL,
  veggies_fk varchar(100) DEFAULT NULL
);

INSERT INTO month_veggies (country_fk, month_fk, veggies_fk)
VALUES ('1','1','7'),('1','1','8'),('1','1','9'),('1','1','10'),('1','1','11'),('1','1','12'),('1','1','13'),('1','1','14'),('1','1','15'),('1','1','16'),('1','1','17'),('1','1','18'),('1','1','19'),('1','1','20'),('1','1','21'),('1','1','22'),('1','1','23'),('1','1','24'),('1','1','25'),('1','1','26'),('1','1','27'),('1','1','28'),('1','1','29'),('1','1','30'),('1','1','31'),('1','1','32'),('1','1','33'),('1','1','34'),('1','1','35'),('1','1','2'),('1','1','5'),('1','1','36'),('1','2','8'),('1','2','9'),('1','2','10'),('1','2','11'),('1','2','13'),('1','2','14'),('1','2','15'),('1','2','16'),('1','2','18'),('1','2','19'),('1','2','20'),('1','2','22'),('1','2','23'),('1','2','24'),('1','2','36'),('1','2','25'),('1','2','26'),('1','2','27'),('1','2','28'),('1','2','29'),('1','2','30'),('1','2','31'),('1','2','32'),('1','2','33'),('1','2','34'),('1','2','35'),('1','2','12'),('1','2','5'),('1','2','17'),('1','2','21'),('1','2','3'),('1','2','4'),('1','3','8'),('1','3','9'),('1','3','10'),('1','3','11'),('1','3','14'),('1','3','15'),('1','3','16'),('1','3','18'),('1','3','19'),('1','3','20'),('1','3','22'),('1','3','23'),('1','3','3'),('1','3','24'),('1','3','4'),('1','3','36'),('1','3','25'),('1','3','26'),('1','3','27'),('1','3','28'),('1','3','29'),('1','3','30'),('1','3','31'),('1','3','33'),('1','3','34'),('1','3','35'),('1','3','12'),('1','3','13'),('1','3','5'),
('1','3','17'),('1','3','32'),('1','4','8'),('1','4','9'),('1','4','10'),('1','4','11'),('1','4','16'),('1','4','17'),('1','4','18'),('1','4','19'),('1','4','20'),('1','4','22'),('1','4','23'),('1','4','3'),('1','4','24'),('1','4','4'),('1','4','36'),('1','4','25'),('1','4','26'),('1','4','27'),('1','4','28'),('1','4','29'),('1','4','30'),('1','4','31'),('1','4','33'),('1','4','34'),('1','4','35'),('1','4','2'),('1','4','12'),('1','4','13'),('1','4','5'),('1','4','14'),('1','4','15'),('1','4','32'),('1','5','8'),('1','5','11'),('1','5','13'),('1','5','16'),('1','5','17'),('1','5','18'),('1','5','19'),('1','5','20'),('1','5','24'),('1','5','36'),('1','5','25'),('1','5','26'),('1','5','27'),('1','5','28'),('1','5','29'),('1','5','30'),('1','5','31'),('1','5','32'),('1','5','33'),('1','5','34'),('1','5','35'),('1','5','2'),('1','5','9'),('1','5','10'),('1','5','5'),('1','5','37'),('1','5','14'),('1','5','22'),('1','6','13'),('1','6','37'),('1','6','16'),('1','6','17'),('1','6','6'),('1','6','31'),('1','6','40'),('1','6','32'),('1','6','35'),('1','6','2'),('1','6','7'),('1','6','39'),('1','6','11'),('1','6','38'),('1','6','17'),('1','6','18'),('1','7','39'),('1','7','38'),('1','7','37'),('1','7','16'),('1','7','17'),('1','7','6'),('1','7','41'),('1','7','31'),('1','7','40'),('1','7','42'),('1','7','2'),('1','7','7'),('1','7','18'),('1','7','19'),('1','7','27'),('1','7','28'),('1','7','32'),('1','8','39'),('1','8','38'),('1','8','37'),('1','8','16'),
('1','8','6'),('1','8','41'),('1','8','31'),('1','8','40'),('1','8','42'),('1','8','2'),('1','8','14'),('1','8','32'),('1','8','2'),('1','9','39'),('1','9','38'),('1','9','37'),('1','9','14'),('1','9','16'),('1','9','6'),('1','9','41'),('1','9','31'),('1','9','40'),('1','9','32'),('1','9','42'),('1','9','2'),('1','9','7'),('1','9','13'),('1','9','24'),('1','9','27'),('1','9','29'),('1','9','30'),('1','10','8'),('1','10','39'),('1','10','12'),('1','10','13'),('1','10','14'),('1','10','16'),('1','10','24'),('1','10','26'),('1','10','41'),('1','10','30'),('1','10','31'),('1','10','40'),('1','10','32'),('1','10','33'),('1','10','34'),('1','10','35'),('1','10','2'),('1','10','11'),('1','10','38'),('1','10','5'),('1','10','37'),('1','10','18'),('1','10','19'),('1','11','8'),('1','11','11'),('1','11','12'),('1','11','13'),('1','11','5'),('1','11','14'),('1','11','15'),('1','11','16'),('1','11','18'),('1','11','19'),('1','11','20'),('1','11','21'),('1','11','22'),('1','11','23'),('1','11','24'),('1','11','26'),('1','11','27'),('1','11','28'),('1','11','29'),('1','11','30'),('1','11','31'),('1','11','32'),('1','11','33'),('1','11','34'),('1','11','35'),('1','11','2'),('1','11','9'),('1','11','39'),('1','11','10'),('1','11','38'),('1','11','17'),('1','11','36'),('1','12','8'),('1','12','9'),('1','12','10'),('1','12','11'),('1','12','12'),('1','12','13'),('1','12','5'),('1','12','14'),('1','12','15'),('1','12','16'),('1','12','17'),('1','12','18'),('1','12','19'),('1','12','20'),('1','12','21'),('1','12','22'),('1','12','23'),('1','12','24'),('1','12','25'),('1','12','26'),('1','12','27'),('1','12','28'),('1','12','29'),('1','12','30'),('1','12','31'),('1','12','32'),('1','12','33');

-- VEGGIES Table
DROP TABLE IF EXISTS veggies;

CREATE TABLE veggies (
  id int NOT NULL AUTO_INCREMENT,
  veggie_name varchar(100) DEFAULT NULL,
  veggie_type varchar(100) DEFAULT NULL,
  veggie_url varchar(200) DEFAULT NULL,
  veggie_description varchar(1000) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO veggies (id, veggie_name, veggie_type, veggie_url, veggie_description)
VALUES (1,'tomato','vegetable','https://www.elhuertodelabuelo.es/37-large_default/tomate-cana-andaluz.jpg', "Getting more tomatoes into your diet may make you less likely to have a stroke, which is when blood flow gets cut off to a part of your brain. Studies suggest that they may ease inflammation, boost your immune system, lower your cholesterol levels, and keep your blood from clotting."),
(2,'carrots','vegetable','https://graneleselmontanes.es/112-large_default/zanahoria-bio-caja-10-kg.jpg', "The carrot (Daucus carota subsp. sativus) is a root vegetable full of fiber, vitamins and antioxidants. Typically orange in color, though purple, black, red, white, and yellow cultivars exist, all of which are domesticated forms of the wild carrot, Daucus carota, native to Europe and Southwestern Asia."),
(3,'asparagus','vegetable','https://www.despensa.es/documents/10180/10736/950979_G.jpg', 'Asparagus has more than one gram of soluble fiber per cup, which lowers the risk of heart disease, and the amino acid asparagine helps the body flush out excess salt. Asparagus has excellent anti-inflammatory effects and high levels of antioxidants, both of which may help reduce the risk of heart disease.'),
(4,'peas','vegetable','https://soycomocomo.es/media/2014/06/pesols.jpg', 'Peas contain heart-friendly minerals including magnesium, potassium and calcium and are also rich in antioxidant nutrients like vitamin C, as well as phytonutrients including carotenoids and flavonols which are heart protective and support cardiovascular function.'),
(5,'broccoli','vegetable','https://thefoodtech.com/wp-content/uploads/2020/07/br%C3%B3colis.jpg', "Broccoli is a nutrient-rich vegetable that may enhance your health in a variety of ways, such as by reducing inflammation, improving blood sugar control, boosting immunity and promoting heart health. However, keep in mind that good health doesn't come from any single food."),
(6,'green bean','vegetable','https://agricultoresenorigen.com/wp-content/uploads/2021/09/judias-verdes-product-01.jpg', "The vegetable helps fight inflammation and is a good source of folate and potassium, which helps regulate blood pressure. Green beans also are a good source of protein and fiber, which helps lower cholesterol, Vadiveloo said. 'Fiber is underconsumed by U.S. adults and children, and it's good for gut health,' she said"),
(7,'swiss chard','vegetable','https://www.cocinista.es/download/bancorecursos/ingredientes/ingrediente-acelga.jpg', "Swiss chard is a highly nutritious vegetable. It may help people maintain healthy blood sugar levels and support heart health. It is an excellent source of vitamin A and vitamin K and a good source of vitamin C and magnesium. It also contains the antioxidants beta-carotene, lutein, and zeaxanthin. Vitamin A plays a significant role in normal formation and maintenance of many organs including the heart, lungs and kidneys."),
(8,'dried garlic','vegetable','https://www.globalcarnica.com/wp-content/uploads/2022/12/Cebolla-blanca-en-escamas-deshidratada.jpg',"Dried garlic contains vitamin C which boosts the immune system. It is high in iodine, which supports healthy thyroid function. Dried garlic is also a good source of iron which helps cells to deliver oxygen throughout the body and improves energy levels."),
(9,'garlic','vegetable','https://colofruitonline.com/wp-content/uploads/2020/12/ajos-tiernos.jpg', "People commonly use garlic for high blood pressure, high levels of cholesterol or other fats in the blood, and hardening of the arteries. It is also used for the common cold, osteoarthritis, and many other conditions, but there is no good scientific evidence to support these uses."),
(10,'artichokes','vegetable','https://www.agroter.es/wp-content/uploads/2021/03/ALCACHOFAS-AGROTER-E2-1.png',"Artichokes are a great source of fiber, which can help keep your digestive system healthy by promoting friendly gut bacteria, reducing your risk of certain bowel cancers, and alleviating constipation and diarrhea. Artichokes contain inulin, a type of fiber which acts as a prebiotic. Artichokes are frequently cited as a superfood, in part because of their high levels of antioxidants. Studies show a number of proven and potential health benefits of artichokes. High blood pressure, or hypertension, can increase the risk of heart disease and stroke."),
(11,'celery','vegetable','https://vilaaurora.es/images/productos/apio.jpg?1613056368', "Celery contains vitamin C, beta carotene, and flavonoids, but there are at least 12 additional kinds of antioxidant nutrients found in a single stalk. It's also a wonderful source of phytonutrients, which have been shown to reduce instances of inflammation in the digestive tract, cells, blood vessels, and organs."),
(12,'sweet potato','vegetable','https://www.hobbysaliplant.com/61-thickbox_default/boniato.jpg', "They're high in fiber and antioxidants, which protect your body from free radical damage and promote a healthy gut and brain. They're also incredibly rich in beta carotene, which is converted to vitamin A to support good vision and your immune system. Of the thousands of vegetables available today, sweet potatoes are considered one of the most nutritious. The orange- (or sometimes purple) fleshed vegetables are loaded with minerals and A, B, and C vitamins. This has led to sweet potatoes being called a superfood by many."),
(13,'borage','vegetable','https://frutascharito.es/292-large_default/borraja.jpg', "Borage flower and leaves are used for fever, cough, and depression. Borage is also used for a hormone problem called adrenal insufficiency, for 'blood purification', to increase urine flow, to prevent inflammation of the lungs, as a sedative, and to promote sweating."),
(14,'pumpkin','vegetable','https://www.citrusgourmet.com/es/195-large_default/calabaza-butternut-12-kg.jpg', "Raw pumpkin has only 15 calories per 1/2 cup, and is full of iron, zinc, and fiber. It's high in vitamin C and beta carotene. Pumpkins are also high in lutein and zeaxanthin, substances that may help prevent the formation of cataracts and reduce the risk of macular degeneration."),
(15,'thistle','vegetable','https://losvalentinesonline.com/wp-content/uploads/2020/10/crd.jpg', "Milk thistle contains compounds that may support skin, liver, and bone health and enhance weight loss. Milk thistle might also help prevent insulin resistance and slow the growth of cancer, among other benefits."),
(16,'dehydrated onion','vegetable','https://i.ebayimg.com/images/g/VU0AAOSwtM5jLaWM/s-l500.jpg', "Dehydrated Onions are very healthy, being relatively high in energy, rich in calcium and riboflavin and have a significant content of protein too. It is easy to store, being light in weight and smaller in bulk than fresh or any other form of processed onion."),
(17,'onion','vegetable','https://tradecorp.mx/wp-content/uploads/2015/06/shutterstock_71561446.jpg', "Onions are loaded with plant chemicals including flavonoids, which have both an antioxidant and anti-inflammatory effect. When consumed regularly and in sufficient quantity, these compounds may help protect against chronic conditions such as cancer and diabetes."),
(18,'parsnip','vegetable','https://blogs.oximesa.es/wp-content/uploads/2020/01/Conoces-la-chiriv%C3%ADa-o-pastinaca.jpg', "Along with vitamin C, parsnips are rich in potassium, a mineral that helps your heart function, balances your blood pressure, and lowers your risk for kidney stones. One serving of parsnips provides about 10 percent of your DRI of potassium."),
(19,'cabbage','vegetable','https://www.ekkomarket.es/184-thickbox_default/col-lisa.jpg', "Cabbage is highly nutritious and rich in vitamin C, fiber, and vitamin K. What's more, some research suggests that it may support digestion, improve heart health, and decrease inflammation. Despite its impressive nutrient content, cabbage is often overlooked."),
(20,'kohlrabi','vegetable','https://img.freepik.com/vector-premium/colinabo_195186-4859.jpg?w=2000', "The vitamins, minerals, and antioxidants in kohlrabi can provide important health benefits. For example, vitamin C helps the body fight off infection and reduce inflammation. Vitamin C can also improve immunity and lower cholesterol. Kohlrabi is also rich in folate, which is an important nutrient for pregnant women because it can help prevent some birth defects."),
(21,'brussels sprouts','vegetable','https://www.hoyverdurascongeladas.com/wp-content/uploads/2018/06/coles-de-bruselas-ampl.jpg', "The fiber in Brussels sprouts—over 3 grams per cup, according to the USDA—helps regulate blood sugar levels, support digestive health, and feed the beneficial gut bacteria. Gut bacteria are tied to positive mood, immunity, and anti-inflammation, according to Harvard University's School of Public Health."),
(22,'cauliflower','vegetable','https://www.comenaranjas.com/images/stories/virtuemart/product/coliflor.jpg', "It's high in vitamins C and K, and is also a good source of folate, which supports cell growth and is essential during pregnancy. Cauliflower is fat-free and cholesterol-free. And it's low in sodium. A one-cup serving contains only 25 calories, 5 grams of carbohydrates and 2 grams of dietary fiber."),
(23,'endive','vegetable','https://okdiario.com/img/recetas/2017/08/20/escarola-2.jpg', "Endive is rich in potassium. This is a mineral that plays an important role in the function of your nerves, muscle, kidney, and heart. Potassium can be found in many foods like fruits, vegetables, dairy, and seafood. Most people don't get enough potassium in their diet."),
(24,'spinach','vegetable','https://www.gastronomiavasca.net/uploads/image/file/3368/w700_espinacas.jpg', "Spinach is a nutritious, leafy green. This vegetable has been shown to benefit health in several ways. Spinach may decrease oxidative stress, improve eye health, and help prevent heart disease and cancer. If you're interested in its health-boosting potential, spinach is an easy food to add to your diet."),
(25,'fennel','vegetable','https://www.gastronomiavasca.net/uploads/image/file/3330/w700_bulbo_de_hinojo.jpg', "Fennel is low in calories but rich in nutrients linked to many health benefits.The main fennel bulb is a plant-based sourceTrusted Source of potassium, sodium, phosphorus, and calcium. It is also high in essential fatty acids and magnesium. People can also use fennel seeds, leaves, and flowers in different ways.Research showsTrusted Source that fennel seeds may have antioxidant, anti-inflammatory, anti-fungal, and antiviral effects. A 2020 systematic review found that digesting these seeds may also stimulate prolactin to help mothers naturally produce breast milk. A person can ingest fennel seeds in dishes or as an extract. People can also steep fennel seeds, leaves, and flowers to make tea. Fennel tea may aid digestion and other gastrointestinal issues such as heartburn, bloating, loss of appetite, and colic in infants."),
(26,'kale','vegetable','https://disfrutaverdura.com/1559-large_default/col-kale-eco-400g.jpg', "Kale is a nutrition superstar due to the amounts of vitamins A, B6, C, K, folate, fiber, carotenoids and manganese it contains. One cup of raw kale has just 20 calories. The Department of Agriculture's MyPlate recommends any child and adult who is over the age of 9 eat at least 1.5-2 cups of dark-green vegetables every week.Kale is a member of the cruciferous vegetable family, along with cauliflower, Brussels sprouts, cabbage, broccoli, collard greens, kohlrabi, rutabaga, turnips and bok choy. These vegetables offer health benefits, including supporting the immune system, regulating blood pressure and potentially reducing the risk of various types of cancer. People who may need to avoid or limit kale intake are those who form oxalate-containing kidney stones or take the blood thinners Coumadin or warfarin. Be sure to check with your health care professional or dietitian if you have questions."),
(27,'lettuce','vegetable','https://delahuertacasa.com/wp-content/uploads/2022/01/lechuga-romana-product-600x397.jpg.webp', ),
(28,'red cabbage','vegetable','https://www.calfruitos.com/es/fotos/pr_135_20170919113923.png', "Like other cruciferous vegetables, red cabbage contains many nutrients that your body needs. All types of cabbage contain a variety of antioxidant compounds that fight harmful molecules and reduce stress on your cells. But red cabbage has higher levels of some types of antioxidants than other types of cabbage. These nutrients are thought to help reduce the risk of health conditions such as cancer, osteoporosis, and heart disease. Red cabbage is particularly rich in anthocyanins, which are a type of flavonoid. Flavonoids are natural substances that plants use to help them do things like attract pollinators and survive droughts. They also have benefits for people who consume them. Some of the potential health benefits of red cabbage include:Heart health. Diets high in anthocyanins, like those found in red cabbage, are linked with lower blood pressure. They're also linked to a reduced risk of cardiovascular (heart and blood vessel) disease.Brain protection. One study linked anthocyanins to increased blood flow in areas of the brain linked to attention, language, and memory. Another suggested they could aid memory and speech in people 70 and over who had mild or moderate dementia."),
(29,'turnips','vegetable','https://www.cucinare.tv/wp-content/uploads/2020/07/Nabo.jpg', "When was the last time you craved a turnip? Never? Fair enough. In comparison to its cousins -- kale, cauliflower, arugula, and cabbage -- the turnip isn't a regular on most menus. But it's got a health profile that makes it worth checking out. Turnips are among the oldest and hardiest vegetables. They grew wild in Siberia when dinosaurs roamed the earth and got an early reputation as a food for poor people and farm animals. Today, many people wouldn't know a turnip if they saw or tasted one. People mistake it most often for the rutabaga, which is a cross between a turnip and cabbage. So here's your turnip 101: It's a root vegetable in the Brassicacae family of mustard plants. It's ready for harvest in the spring and fall. The most common turnip is light purple on top and white on the bottom, but there are more than 30 kinds with varying shapes and colors. Some are sweet, like a carrot, while others taste more like a potato. Unlike most other vegetables, you can eat both the turnip's root and the leafy greens attached to the top. They're both good for you."),
(30,'pack choi','vegetable','https://www.eladerezo.com/wp-content/uploads/2011/01/pak-choi-1.jpg'),
(31,'potato','vegetable','http://www.frutas-hortalizas.com/img/fruites_verdures/presentacio/59.jpg', "Potatoes are a starchy vegetable that can benefit health. They contain antioxidants, as well as vitamins and minerals, including vitamin C, B6, and potassium, which can help with heart and digestive health."),
(32,'parsley','vegetable','https://www.cocinista.es/download/bancorecursos/ingredientes/perejil.jpg', "The following possible health benefits have been linked to consuming parsley. Preventing cancer. Flavonoids are naturally-occurring plant compounds that can counter disease-causing agents in the body. Myricetin is a flavonoid found in parsley and other plants. It has been shown to help prevent skin cancer. Parsley contains one of the highest concentrations of myricetin per 100 gramsTrusted Source. Studies have shownTrusted Source that parsley and other green herbs and vegetables can block the cancer-causing effects of heterocyclic amines. These are chemical compounds that have cancer-causing qualities. They are generated when meat is grilled at high temperatures.Those who prefer charred steak should pair it with green vegetables, such as parsley, to help reduce these potentially harmful effects. Apigenin is a natural chemical found in parsley. In a 2015 reviewTrusted Source, it was shown to decrease tumor size in an aggressive form of breast cancer. Researchers believe that apigenin could be a promising non-toxic cancer treatment in the future.Protecting against diabetes,The myricetin present in parsley has also been examined for use in the treatment and prevention of diabetes. Laboratory and animal studies have demonstrated that myricetin can lower blood sugar levels and decrease insulin resistance. It also appears to provide anti-inflammatory effects and remove excess fat from the blood. Improving bone health. Low vitamin K intake has been associated with a higher risk of bone fracture. Consuming an adequate amount of vitamin K may improve bone health by improving calcium absorption and reducing the excretion of calcium in the urine. In a recent meta-analysis, subjects with the highest levels of vitamin K experienced 22 percent fewer fracturesTrusted Source than those with low levels. Ten sprigs of parsley are enough to reach the recommended daily intake of vitamin K. Eating a range of fruits, vegetables, and herbs is linked to a reduced risk of health problems. A diet with higher quantities of natural foods and fewer manufactured foods is more likely to result in better overall health. One chemical or vitamin is not likely to provide the same health benefits on its own or in supplement form. It provides more benefit to consume food in its original form."),
(33,'leek','vegetable','https://losvalentinesonline.com/wp-content/uploads/2020/09/puerros_3952454.png', "Some of the main health benefits of raw leek consumption are: 1. Anticancer properties 2. Blood Pressure Reduction 3. Boost skin and hair health 4. Diuretic properties. Cancer. Anticancer properties of leeks and other allium vegetables, like the sulfur-containing compounds, have been studied and published in the Journal of the National Cancer Institute. According to that research, men receiving the highest amount of allium vegetables had a lower risk of developing prostate cancer. Other studies have also shown that the same risk reduction is possible for stomach and colon cancers. Skin and Hair. Leeks are a source of vitamin C . Vitamin C participates in collagen building which is responsible for the good health and structure of our skin and hair. Contribute to blood pressure reduction.Leeks are a source of potassium. According to studies, people who regularly consume increased amounts of potassium and, at the same time, have a poor sodium diet tend to have lower blood pressure levels.Diuretic properties. Leeks may have a diuretic action on our bodies. They help water and sodium expelled from the body as urine. This is quite important, mainly for people who suffer from hypertension."),
(34,'radish','vegetable','https://mercagarden.com/523-large_default/rabano-o-rabanito.jpg', "Radishes are root vegetables that belong to the Cruciferae or mustard family. Their skins can be red, black, yellow, purple, and pink, and they have a slightly sweet, peppery taste. They range in shape from short and round to long and narrow. Radishes are likely native to Southeast or Central Asia. The Ancient Greeks and Romans also used them for food and medicinal purposes. Several thousand years ago, people began to cultivate the wild radish, and it eventually spread to new lands."),
(35,'beets','vegetable','https://soycomocomo.es/media/2015/11/remolacha.jpg', "Beets are known for their slight heart shape, bright colors, earthy flavor, and the ability to stain everything in sight when sliced in preparation for a meal. They are full of essential vitamins, minerals, and plant compounds, many of which have medicinal properties."),
(36,'fava beans','vegetable','https://media.justo.mx/products/10693-Habas-limpias-1.jpg', "Legumes are known for their health benefits. Fava beans, like many other legumes, are packed with nutrients that boost your health. The nutrients in fava beans can aid in weight loss, help prevent some illnesses, and promote healthy growth. Protein. One cup of cooked fava beans contains almost a third of your daily protein needs. Protein is one of the most important nutrients in your diet. Eating high-protein foods can help you feel fuller for longer. Protein also helps grow and maintain your muscles.Vegetarians, vegans, and people with lactose intolerance can't eat high-protein foods from animals like meat, cheese, or eggs. Adding fava beans and other plant sources in your diet can help make sure you're getting enough protein. Folate. One cup of fava beans meets almost half of your daily folate needs. Folate is a type of vitamin that helps your body create DNA and make new cells. "),
(37,'zucchini','vegetable','https://comedelahuerta.com/wp-content/uploads/2019/09/CALABACIN-ECOLOGICO-COMEDELAHUERTA-1.jpg', "Zucchini is packed with many important vitamins, minerals, and antioxidants. It has a high fiber content and a low calorie count. Fiber plays an important role in digestion and may limit the likelihood of suffering from a variety of GI issues. Cancer Prevention. Zucchini contains zeaxanthin and several other compounds that can play a role in preventing oxidative stress. This, in turn, may limit the likelihood of developing cancer. Diabetes Prevention and Management. Zucchini is rich in vitamin B6. Research suggests that this vitamin can help with regulating blood glucose. The vitamin may even play a protective role against diabetes.Improved Eye Health. Compounds such as lutein and zeaxanthin protect the eye's cells by filtering blue light wavelengths. A diet rich in these compounds may reduce the risk of developing cataracts or other eye-related health problems."),
(38,'eggplant','vegetable','https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201811/26/00118107800080____6__600x600.jpg', "Eggplant is highly nutritious with beneficial vitamins, minerals, fiber, and antioxidants. Its regular consumption may improve digestion, promote strong and healthy bones, aid weight loss, improve digestive health, prevent anemia, lower the risk of developing cancer, regulate sugar levels, and improve brain function."),
(39,'basil','vegetable','https://fruteriadevalencia.com/wp-content/uploads/2015/01/ALBAHACA-buena-510x407.jpg', "The eugenol in basil can block calcium channels, which may help to lower blood pressure. Its essential oils can help lower your cholesterol and triglycerides. Basil also contains magnesium, which can help improve your blood flow by allowing your muscles and blood vessels to relax."),
(40,'cucumber','vegetable','https://www.recetasnestlecam.com/sites/default/files/2022-04/que-es-el-pepino.jpg', "All that water in cucumbers can help keep you hydrated. Plus, the fiber boost they give you helps you stay regular and avoid constipation. The vitamin K helps blood clot and keep your bones healthy. Vitamin A has many jobs, like helping with vision, the immune system, and reproduction."),
(41,'corn','vegetable','https://www.supermasymas.com/blog/wp-content/uploads/2021/04/art_5_1.jpg', "Corn is a staple food, one of the most commonly eaten and grown in the world. There are more than 200 varieties grown in the United States alone, where corn on the cob is a popular tradition among many families. In Latin America the husks are used to make tamales, and ground corn is used as a base for many traditional recipes, including tortillas. Since corn is naturally gluten-free, it's a good choice to use in place of wheat. It's also loaded with important vitamins, minerals, and antioxidants that can help your health in a number of ways. "),
(42,'peppers','vegetable','https://www.hogarmania.com/archivos/201211/440-nutricion-pimientos-xl-668x400x80xX.jpg', "Peppers have a lot going for them. They're low in calories and are loaded with good nutrition. All varieties are excellent sources of vitamins A and C, potassium, folic acid, and fiber. Plus, the spicy ones liven up bland food, making it more satisfying.");

-- FRUITS Table
DROP TABLE IF EXISTS fruits;

CREATE TABLE fruits (
  id int NOT NULL AUTO_INCREMENT,
  fruit_name varchar(100) DEFAULT NULL,
  fruit_url varchar(100) DEFAULT NULL,
  fruit_description varchar(1000) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO fruits (id, fruit_name, fruit_url, fruit_description) 
VALUES (1,'avocado',"https://frutascharito.es/702-large_default/aguacates-unidad.jpg", "Avocados have been commended as an example of a nutrient-dense food, with one half of the fruit counting towards your five-a-day. Avocados are an excellent source of monounsaturated fat and vitamin E, and are a good source of folate. They also supply more soluble fibre than other fruit and contain a number of useful minerals including iron, copper and potassium."),
(2,'guava',"https://frutascharito.es/758-large_default/guayabas.jpg", "They protect against infectious diseases and serve as a remedy for oral issues. Guavas enhance immunity due to their high vitamin C content, aid in diabetes management, promote heart health, assist in weight loss, improve digestion, boost brain function, enhance skin health, relieve stress, and benefit pregnant women."),
(3,'kiwi',"https://frutascharito.es/1443-large_default/kiwis-unidad.jpg", "Kiwis are high in Vitamin C  and dietary fiber and provide a variety of health benefits. This tart fruit can support heart health, digestive health, and immunity. The kiwi is a healthy choice of fruit and is rich with vitamins and antioxidants. Its tart flavor, pleasing texture, and low calorie count make it a delicious and healthy option for snacking, sides, or a unique dessert."),
(4,'lemon',"https://frutascharito.es/168-large_default/limones.jpg", "Lemons contain about 50 milligrams of vitamin C, which is over half the amount of vitamin C needed in your daily diet. Vitamin C is an antioxidant, which helps protect cells from damage. Vitamin C also helps your body make collagen for your skin, helps your body absorb iron, and supports your immune system."),
(5,'tangerine',"https://frutascharito.es/108-large_default/clementinas-naturales-sin-tratar.jpg", "Tangerines are a nutrient-rich citrus fruit that may provide numerous benefits to your health. They're packed with antioxidants, which may support immunity, provide cancer-fighting properties, and improve brain, skin, and heart health. Tangerines are also sweet and refreshing and can be enjoyed in numerous dishes."),
(6,'orange',"https://frutascharito.es/105-large_default/naranjas-de-mesa.jpg", "Boosts the body's immune system to protect against viruses and germs. Improves iron absorption and fights anemia. Slows age-related macular degeneration (AMD), which can lead to vision loss. Lowers blood pressure and cortisol, the stress hormone."),
(7,'papaya',"https://frutascharito.es/341-large_default/papayon-de-brasil.jpg", "Eating papaya every morning can be very beneficial for your health as well as skin. It is rich in Vitamin C, which helps in repairing skin cells. At the same time, the antioxidants present in it help protect the skin from free radical damage. It detoxes the body, thereby reducing skin problems."),
(8,'banana',"https://frutascharito.es/145-large_default/platanos-de-canarias.jpg", "Bananas are an excellent source of potassium, a vital mineral and electrolyte in the body that carries a small electrical charge. These charges cause nerve cells to send out signals for the heart to beat regularly and muscles to contract. They also contain vitamins A and C, which are essential for healthy, youthful-looking skin. Vitamin A can help reduce fine lines and wrinkles, while vitamin C can help brighten and even out your skin tone. So, if you want to keep those wrinkles at bay, just eating bananas daily will do the trick for you."),
(9,'grapefruit',"https://frutascharito.es/703-large_default/pomelos-rosas-unidad.jpg", "Grapefruits are full of vitamins, minerals, and other nutrients and low in calories. They're popular as a breakfast food and as part of weight loss diets. They also support the immune system, help with weight management and reduce the risk of kidney stones"),
(10,'khaki',"https://frutascharito.es/122-large_default/kakis.jpg", "Persimmons are sweet, versatile fruits full of vitamins, minerals, fiber, and beneficial plant compounds. What's more, they may promote heart health, reduce inflammation, support healthy vision, and keep your digestive system healthy. Plus, they are tasty and pair well with many foods."),
(11,'quince',"https://frutascharito.es/231-large_default/membrillos.jpg", "It's rich in vitamin C, fiber and antioxidants. It also contains a small amount of several other micronutrients, including copper, potassium and iron. Potential quince benefits include decreased bacterial growth, improved heart health, faster wound healing, and relief from constipation and GERD."),
(12,'dragon fruit',"https://frutascharito.es/1431-large_default/pitahaya-roja.jpg", "Dragon fruit is high in vitamin C and other antioxidants, which are good for your immune system. It can boost your iron levels. Iron is important for moving oxygen through your body and giving you energy, and dragon fruit has iron. And the vitamin C in dragon fruit helps your body take in and use the iron."),
(13,'grenade',"https://frutascharito.es/1428-large_default/granadas-para-zumo-unidad.jpg", "Pomegranates are in season from September to November, but their long shelf life means you can usually find them in grocery stores until January. You can find pomegranate juice year-round, though. Pomegranates can have up to three times more antioxidants than green tea or red wine. Antioxidants protect our cells from damage caused by free radicals and reduce inflammation. Other health benefits of pomegranates include better heart health, that it improves diabetes control and it possibly lowers the risk of cancer."),
(14,'medlar',"https://frutascharito.es/150-large_default/nisperos.jpg", "The medlar fruit is rich in amino acids, tannins, sugars, pectins, and organic acids that combine to give it its distinctive sweet yet tart flavor. This fruit can be used to treat intestinal infections, menstruation irregularities, diarrhea, bloating, Alzheimer's disease."),
(15,'strawberry',"https://frutascharito.es/172-large_default/freson.jpg", "Strawberries are rich in vitamin C and other antioxidants, which help reduce the risk of serious health conditions like cancer, diabetes, stroke, and heart disease. It's also an excellent source of: Magnesium. Phosphorous."),
(16,'cherries',"https://frutascharito.es/1566-large_default/picotas.jpg", "Cherries are nutrient-rich, low in calories and are a valuable addition to your diet for numerous reasons. These include: They're low-GI (glycaemic index), a heart-healthy choice, the may reduce blood pressure, may help manage cholesterol, may help manage blood sugar levels, may help inflammatory conditions, may enhance recovery after exercise, may improve sleep, may help those with gout and may help prevent cancer."),
(17,'apricot',"https://frutascharito.es/151-large_default/albaricoques.jpg", "Apricots are small stone fruit or drupes—thin-skinned fruits with a stone in the center that holds a seed—popularly consumed fresh or dried. Their petite size makes them great for snacking, while the dried version is great for throwing in a trail mix for a fiber boost on the go. Besides fiber, their vitamin and antioxidant profile promotes various facets of health. Here are the benefits of apricots, their nutrition facts, risks, and tips for making them a regular part of your diet. "),
(18,'plum',"https://frutascharito.es/1070-large_default/ciruelas-negras.jpg", "The vitamin C in plums helps your body heal, build muscle, and form blood vessels. It's great for your eyes, too.Here are other ways that plums are good for your health: Heart disease.Phytochemicals and nutrients in plums lower the inflammation that triggers heart disease. Anxiety. A plum a day may keep anxiety away. When your antioxidants are low, anxiety can be high. Constipation. Plums, like prunes, can also help keep things moving through your system. They have a lot of sorbitol, a sugar alcohol that acts as a natural laxative. High blood pressure and stroke. The potassium in plums is good for blood pressure control in two ways. It helps your body get rid of sodium when you pee, and it lessens tension in the walls of your blood vessels. When your blood pressure is low, your odds of getting a stroke go down. Antioxidants. These substances protect the body against the cell and tissue damage that can lead to diabetes, Alzheimer's disease, Parkinson's disease, and cancer. Blood sugar. Plums are chock full of fiber, which helps slow down a blood sugar spike after you eat carbs. They can also boost your body's production of adiponectin, a hormone that helps regulate your blood sugar levels. Bone health. Some studies show that prunes (dried plums) may help reduce bone loss and may even preserve it."),
(19,'peach',"https://frutascharito.es/157-large_default/melocotones.jpg", "Consumption of fruits like peaches that are rich in vitamin A, are known to offer protection from lung and oral cancers. They contain many vital minerals such as potassium, fluoride and iron. Potassium is an important component of cell and body fluids that help regulate heart rate and blood pressure."),
(20,'nectarine',"https://frutascharito.es/1462-large_default/nectarinas.jpg", "They are low in calories but can provide fiber, vitamin C, potassium and niacin. Thanks to their impressive nutrient profile, nectarines can strengthen eye, immune, heart and digestive health; may help with weight loss; can lower blood sugar levels; and may even help kill off cancer cells."),
(21,'donut peach',"https://frutascharito.es/158-large_default/paraguayas.jpg", "The Donut Peach, also known as the Saturn or Saucer Peach, is a sweet, delicious, and nutritious stone fruit. This peach is packed with vitamin C, fiber, and potassium, and is said to improve skin, heart, and cardiovascular health."),
(22,'watermelon',"https://frutascharito.es/187-large_default/sandia-1-2-unid.jpg", "It has a very high water content and provides nutrients like lycopene, citrulline, and vitamins A and C. Studies suggest that this sweet, red melon may even boost heart health, reduce muscle soreness, and decrease inflammation, though more research is needed."),
(23,'raspberry',"https://frutascharito.es/139-large_default/frambuesas.jpg", "They provide potassium, essential to heart function, and proven to lower blood pressure. The omega-3 fatty acids in raspberries can help prevent stroke and heart disease. They also contain a mineral called manganese, which is necessary for healthy bones and skin and helps regulate blood sugar."),
(24,'melon',"https://frutascharito.es/335-large_default/melon-piel-sapo-unidad.jpg", "Summer is the season for melons! These juicy, sweet fruits are packed with nutrients and make the perfect snack or light meal. Melons are low in calories, fat, and sodium, and they are a good source of dietary fiber, vitamins A, C, and B6, and potassium. They also contain antioxidants that can help protect your cells from damage."),
(25,'blueberry',"https://frutascharito.es/144-large_default/arandanos.jpg", "If consumed daily, a person will likely have an increased antioxidant and anti-inflammatory food intake, which may lead to improved heart health, digestive health, blood sugar regulation, cancer risk and chronic disease risk"),
(26,'fig',"https://frutascharito.es/1477-large_default/higos-chumbos.jpg", "Figs have many potential benefits, including promoting digestive and heart health, along with potentially helping manage blood sugar levels. Fresh figs contain some calories from natural sugar, but having a few figs is a reasonable, low calorie snack or addition to a meal. On the other hand, dried figs are high in sugar and rich in calories, as the sugar becomes concentrated when the fruits are dried. Figs also contain small amounts of a wide variety of nutrients, but they’re particularly rich in copper and vitamin B6. Copper is a vital mineral that’s involved in several bodily processes, including metabolism and energy production, as well as the formation of blood cells, connective tissues, and neurotransmitters. Vitamin B6 is a key vitamin necessary to help your body break down dietary protein and create new proteins. It also plays an important role in brain health."),
(27,'mango',"https://www.agroponiente.com/wp-content/uploads/2021/08/mango-Agroponiente.png", "Mango is native to India and Southeast Asia, and people have cultivated it for over 4,000 years. Hundreds of types of mango exist, each with its own characteristic taste, shape, size, and color. Mango is low in calories yet high in nutrients — particularly vitamin C, which aids immunity, iron absorption, and cell growth and repair."),
(28,'apple',"https://frutascharito.es/1116-large_default/manzanas-granny-smith.jpg", "From sweet red varieties, like Red Delicious, Fuji, or Gala, to tangy green ones, like Granny Smith — my favorite with lime juice and a little salt when I want a savory snack — there is an apple for everyone. They’re commonly used in recipes like pies, cookies, muffins, jam, salads, oatmeal, or smoothies. They also make a great snack or wedged and smeared with nut butter. In addition to their culinary versatility and numerous colors and flavors, apples are an exceptionally healthy fruit with many research-backed benefits."),
(29,'grapes',"https://frutascharito.es/62-large_default/uvas-negras-sin-semilla.jpg", "Grapes provide both fibre and potassium, which are helpful in their support of heart function including blood pressure. The polyphenols in grapes including resveratrol and quercetin are also thought to benefit the cardiovascular system, protecting it from inflammatory and oxidative damage."),
(30,'lime',"https://th.bing.com/th/id/OIP.GrXQjizTdsNDebsCeMs82QHaHa?pid=ImgDet&rs=1", "Limes are high in vitamin C and antioxidants — both of which may offer health benefits. Eating limes or drinking the juice may improve immunity, reduce heart disease risk factors, prevent kidney stones, aid iron absorption, and promote healthy skin. Avoid limes if you're allergic to citrus fruit."),
(31,'custard apple',"https://frutascharito.es/1463-large_default/chirimoya-unidad.jpg", "Have you ever heard of a custard apple? This fruit, also called cherimoya, sitaphal, or sugar apple, is a type of tropical fruit known for its sweet flavor and vanilla-like smell. But beyond their luscious smell and texture, some believe they contain additional health benefits which mostly stem from their antioxidant content. The leaves of the custard apple are even used as a form of natural medicine in many parts of the world. Custard apples originated in South America and the West Indies, and were an important part of the diet of indigenous peoples in those areas. Today, custard apples are cultivated in Asia, Australia, Spain, Israel, India, and other warm climates. The name custard apple actually refers to both the fruit and the deciduous tree that grows it. While it holds the shape of a typical apple, a custard apple has green, leathery skin that is bumpy and heavily dimpled. Inside, the pulp is white or yellowish, sweet, and very soft in texture. The inside of a custard apple has large black seeds that represent watermelon seeds.");

-- Comparative TABLE fruits of month
DROP TABLE IF EXISTS month_fruits;

CREATE TABLE month_fruits (
  country_fk varchar(100) DEFAULT NULL,
  month_fk varchar(100) DEFAULT NULL,
  fruits_fk varchar(100) DEFAULT NULL
);

INSERT INTO month_fruits (country_fk, month_fk, fruits_fk)
  VALUES ('1','1','1'),('1','1','2'),('1','1','3'),('1','1','4'),('1','1','5'),('1','1','6'),('1','1','7'),('1','1','8'),('1','1','9'),('1','1','10'),('1','1','11'),('1','1','12'),('1','2','4'),('1','2','5'),('1','2','6'),('1','2','1'),('1','2','3'),('1','2','2'),('1','2','11'),('1','2','7'),('1','2','12'),('1','3','5'),('1','3','6'),('1','3','8'),('1','3','1'),('1','3','4'),('1','3','3'),('1','3','14'),('1','3','9'),('1','4','6'),('1','4','14'),('1','4','8'),('1','4','1'),('1','4','4'),('1','4','15'),('1','4','5'),('1','5','16'),('1','5','15'),('1','5','6'),('1','5','1'),('1','5','17'),('1','5','18'),('1','5','4'),('1','5','5'),('1','5','19'),('1','5','20'),
('1','5','21'),('1','5','22'),('1','6','18'),('1','6','15'),('1','6','19'),('1','6','17'),('1','6','16'),('1','6','1'),('1','6','23'),('1','6','24'),('1','6','6'),('1','6','14'),('1','7','23'),('1','7','15'),('1','7','19'),('1','7','25'),('1','7','18'),('1','7','1'),('1','7','17'),('1','7','26'),('1','7','12'),('1','8','23'),('1','8','15'),('1','8','26'),('1','8','25'),('1','8','18'),('1','8','27'),('1','8','28'),('1','8','20'),('1','8','7'),('1','8','21'),('1','8','12'),('1','8','29'),('1','9','27'),('1','9','28'),('1','9','24'),('1','9','23'),('1','9','26'),('1','9','31'),('1','9','18'),('1','9','15'),('1','9','13'),('1','9','2'),('1','9','3'),('1','9','30'),('1','9','5'),('1','9','19'),('1','10','13'),('1','10','2'),('1','10','3'),('1','10','31'),('1','10','23'),('1','10','1'),('1','10','10'),('1','10','15'),('1','10','26'),('1','10','4'),('1','10','19'),('1','10','24'),('1','10','9'),('1','10','22'),('1','11','31'),('1','11','13'),('1','11','2'),('1','11','1'),('1','11','10'),('1','12','31'),('1','12','2'),('1','12','3'),('1','12','4'),('1','12','5'),('1','12','1'),('1','12','10'),('1','12','11'),('1','12','6'),('1','12','7'),('1','12','12'),('1','12','8'),('1','12','9'),('1','12','13'),('1','12','30'),('1','12','27'),('1','12','28'),('1','12','29');


-- COUNTRIES Table
DROP TABLE IF EXISTS countries;

CREATE TABLE countries (
  id int NOT NULL AUTO_INCREMENT,
  country_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO countries (id, country_name)
VALUES (1,'Spain'),(2,'Chile');